# Generated by Django 4.1 on 2022-08-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BLANKSCREEN",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
                ("emptypoints", models.IntegerField()),
                ("screen", models.CharField(max_length=30)),
                ("viewPoint", models.CharField(max_length=30)),
                ("selector", models.CharField(max_length=100)),
            ],
        ),
    ]
