# Generated by Django 4.1 on 2022-08-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="firstInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
                ("inputdelay", models.IntegerField()),
                ("duration", models.IntegerField()),
                ("starttime", models.IntegerField()),
                ("selector", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="jsError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
                ("errortype", models.CharField(max_length=30)),
                ("message", models.CharField(max_length=200)),
                ("filename", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=100)),
                ("stack", models.CharField(max_length=100)),
                ("selector", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="paint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
                ("firstpaint", models.IntegerField()),
                ("firstcontentfulpaint", models.IntegerField()),
                ("firstmeaningfulpaint", models.IntegerField()),
                ("largestcontentfulpaint", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="resourceError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
                ("errortype", models.CharField(max_length=30)),
                ("filename", models.CharField(max_length=100)),
                ("tagname", models.CharField(max_length=100)),
                ("selector", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="timing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
                ("connecttime", models.IntegerField()),
                ("ttfbtime", models.IntegerField()),
                ("responsetime", models.IntegerField()),
                ("parsedomtime", models.IntegerField()),
                ("domcontentloadedtime", models.IntegerField()),
                ("timetointeractive", models.IntegerField()),
                ("loadtime", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="xhr",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
                ("eventtype", models.CharField(max_length=30)),
                ("pathname", models.CharField(max_length=300)),
                ("status", models.CharField(max_length=300)),
                ("duration", models.IntegerField()),
                ("response", models.CharField(max_length=300)),
                ("params", models.CharField(max_length=300)),
            ],
        ),
    ]
