# Generated by Django 4.1 on 2022-08-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0002_firstinput_jserror_paint_resourceerror_timing_xhr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blankscreen",
            name="emptypoints",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="firstinput",
            name="duration",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="firstinput",
            name="inputdelay",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="firstinput",
            name="starttime",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="paint",
            name="firstcontentfulpaint",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="paint",
            name="firstmeaningfulpaint",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="paint",
            name="firstpaint",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="paint",
            name="largestcontentfulpaint",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="timing",
            name="connecttime",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="timing",
            name="domcontentloadedtime",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="timing", name="loadtime", field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="timing",
            name="parsedomtime",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="timing",
            name="responsetime",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="timing",
            name="timetointeractive",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="timing", name="ttfbtime", field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="xhr", name="duration", field=models.CharField(max_length=30),
        ),
    ]
