# Generated by Django 4.1 on 2022-08-16 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0003_alter_blankscreen_emptypoints_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blankscreen", old_name="emptypoints", new_name="emptyPoints",
        ),
        migrations.RenameField(
            model_name="firstinput", old_name="selector", new_name="Selector",
        ),
        migrations.RenameField(
            model_name="firstinput", old_name="inputdelay", new_name="inputDelay",
        ),
        migrations.RenameField(
            model_name="firstinput", old_name="starttime", new_name="startTime",
        ),
        migrations.RenameField(
            model_name="jserror", old_name="errortype", new_name="errorType",
        ),
        migrations.RenameField(
            model_name="paint",
            old_name="firstcontentfulpaint",
            new_name="firstContentfulPaint",
        ),
        migrations.RenameField(
            model_name="paint",
            old_name="firstmeaningfulpaint",
            new_name="firstMeaningfulPaint",
        ),
        migrations.RenameField(
            model_name="paint", old_name="firstpaint", new_name="firstPaint",
        ),
        migrations.RenameField(
            model_name="paint",
            old_name="largestcontentfulpaint",
            new_name="largestContentfulPaint",
        ),
        migrations.RenameField(
            model_name="resourceerror", old_name="errortype", new_name="errorType",
        ),
        migrations.RenameField(
            model_name="resourceerror", old_name="tagname", new_name="tagName",
        ),
        migrations.RenameField(
            model_name="timing", old_name="connecttime", new_name="connectTime",
        ),
        migrations.RenameField(
            model_name="timing",
            old_name="domcontentloadedtime",
            new_name="domContentLoadedTime",
        ),
        migrations.RenameField(
            model_name="timing", old_name="loadtime", new_name="loadTime",
        ),
        migrations.RenameField(
            model_name="timing", old_name="parsedomtime", new_name="parseDOMTime",
        ),
        migrations.RenameField(
            model_name="timing", old_name="responsetime", new_name="responseTime",
        ),
        migrations.RenameField(
            model_name="timing",
            old_name="timetointeractive",
            new_name="timeToInteractive",
        ),
        migrations.RenameField(
            model_name="timing", old_name="ttfbtime", new_name="ttfbTime",
        ),
        migrations.RenameField(
            model_name="xhr", old_name="eventtype", new_name="eventType",
        ),
    ]
