# Generated by Django 4.1 on 2022-08-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0004_rename_emptypoints_blankscreen_emptypoints_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blankscreen",
            name="timestamp",
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name="firstinput",
            name="timestamp",
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name="jserror",
            name="timestamp",
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name="paint",
            name="timestamp",
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name="resourceerror",
            name="timestamp",
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name="timing",
            name="timestamp",
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name="xhr",
            name="timestamp",
            field=models.CharField(default=0, max_length=30),
        ),
    ]
