# Generated by Django 4.1 on 2022-08-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0005_blankscreen_timestamp_firstinput_timestamp_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="fetch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
                ("startTime", models.CharField(max_length=30)),
                ("url", models.CharField(max_length=30)),
                ("method", models.CharField(max_length=30)),
                ("endTime", models.CharField(max_length=30)),
                ("duration", models.CharField(max_length=30)),
                ("status", models.CharField(max_length=100)),
                ("success", models.CharField(max_length=30)),
                ("response", models.CharField(max_length=100)),
                ("timestamp", models.CharField(default=0, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="pv",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
                ("startTime", models.CharField(max_length=30)),
                ("pageURL", models.CharField(max_length=30)),
                ("referrer", models.CharField(max_length=30)),
                ("uuid", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="stayTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kind", models.CharField(max_length=30)),
                ("type", models.CharField(max_length=30)),
                ("stayTime", models.CharField(max_length=30)),
                ("pageURL", models.CharField(max_length=30)),
                ("uuid", models.CharField(max_length=30)),
            ],
        ),
    ]
