# Generated by Django 4.1 on 2022-08-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0006_fetch_pv_staytime"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pv", name="uuid", field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="staytime", name="uuid", field=models.CharField(max_length=40),
        ),
    ]
