# Generated by Django 4.1 on 2022-08-22 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0007_alter_pv_uuid_alter_staytime_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="pv",
            name="timestamp",
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name="staytime",
            name="timestamp",
            field=models.CharField(default=0, max_length=30),
        ),
    ]
