# Generated by Django 4.1 on 2022-08-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0008_pv_timestamp_staytime_timestamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="timing",
            name="dnsTime",
            field=models.CharField(default="0", max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timing",
            name="domReady",
            field=models.CharField(default="0", max_length=30),
            preserve_default=False,
        ),
    ]
