# Generated by Django 4.1 on 2022-08-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0010_rename_response_fetch_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="xhr",
            name="method",
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
